### ISSUE TITLE
pororo 설치 문제 

### ISSUE THREAD

**Issue by SidViciouz** [minor-league/minor-league#9]
pororo가 fairseq문제로 설치가 안됩니다.
conda환경 python버전도 3.6으로 낮춰서 해보고 시도해봤지만.. 다른 사람들도 많이 겪는 문제인 것 같습니다.
지금 생각으로는 pororo사용하기는 어려울 것 같습니다.

**Comment by limdongjin** [comment]
해결했습니다. pythorch, conda, pororo 모두 의존성이 너무 복잡한 라이브러리라서 로컬에서 바로 작업하기는 어려움이 있죠.
로컬에서 작업하는 대신 도커에서 작업하면 깔끔합니다. 
아래에 환경 설정 방법 공유합니다. 도커 이미지를 이용한 방법이기때문에, 아마도 잘 동작할거에요.

도커 환경에서 pororo 기능들을 테스트한 결과도 공유합니다. 대부분의 기능은 잘 작동합니다. 자세한 내용은 pororo-demo.ipynb 참고하세요
- Word2Vec
- Word Embedding
- NER
- Summarization,
- Semantic Analysis
- Review Scoring
- Machine Reading Comprehension
- Sentence Embedding
- Zero-shot Topic
- 등등 

1.  [pororo+docker 환경 설정](https://github.com/minor-league/minor-league/blob/main/doc/pororo_setup_with_docker.md)
2. [pororo-demo.ipynb](https://github.com/minor-league/minor-league/blob/main/doc/pororo-demo.ipynb)
